# A tiny standard (one public network) network configuration
subnets: [1]
topology: [[ 1, 1],[1,1]]
sensitive_machines: [[1, 0, 10]]
num_services: 1
service_exploits:
  1:
    - 0.8
    - 1
machine_configurations:
  (1, 0): [1]
# two row for each connection between subnets as defined by topology
# one for each direction of connection
# list which services to allow
firewall:
  (0, 1): [1]
  (1, 0): []